modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
[[mods]]
modId="waxed"
displayName="Waxed"
version="0.1a-Forge-1.20.1"
logoFile="waxed_logo.png"
authors="Im_Maker"
credits=""
description='''
Adds wax blocks, wax pillars and now you can wax/unwax some blocks like copper!
'''
[[dependencies.wax_it]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wax_it]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.2)"
    ordering="NONE"
    side="BOTH"
